### ISSUE TITLE
Don't download a 129MB file automatically

### ISSUE THREAD

**Issue by vossad01** [feross/webtorrent.io#113]
Original report of issue was at feross/webtorrent#815

In my case I am on a usage-caped satellite Internet connection.  It is rather hard to visit the website to learn about webtorrent because of the data that will be consumed while I try to read the webpage.

The suggestions proposed by @franciscop on the original issue were:

* Download a 2-3MB file. However this is not so cool as you cannot see the video itself, but much better than using the user's data plan.
* Detect the device/screen and choose to download only on desktop. However this is probably error-phrone.
* Add a "stop" button (or a "start" one) so the visitors can toggle the torrent download at will.

Note: I am not a fan of the second one because there are many cases (such as mine) where you do not want the automatic download on a desktop either.

**Comment by feross** [comment]
We added the second approach. There is an explicit "start" button if your window size is small enough. I suggest using that. Sorry that there's not a better solution for you.

<img width="624" alt="screen shot 2017-01-29 at 12 18 17 pm" src="https://cloud.githubusercontent.com/assets/121766/22407528/08e8f316-e61d-11e6-8015-8f6c82a9535b.png">
